--- 
- name: Install Apache and Upload my Home Page
  hosts: all 
  become: yes
 
  vars:
    source_file: ./MyWebSite/index.html
    destin_file: /var/www/html

  tasks: 
- name: Install Apache Web Server
  yum: name=httpd state=latest

- name: Copy HomePage file to Web Server 
  copy: src={{ source_file }} dest={{ destin_file }} mode=0555

- name: Start Web Server service 
  service: name=httpd state=sterted enabled=yes

handlers: 
- name: Restart Apache
  service: name=httpd state=restarted 

#playbook,to install a simple Apache server
