---

- name: My playbook,to print messages in variables
   hosts: all
   become: yes

  vars:
   message1:Hello
   message2:World
   secret:hty57685hty57685

  tasks: 
- name: Print Variables message1
   debug:
   var: message1 

- debug:
   msg: "Secret word: {{ secret }}"

- debug:
   msg: "Owner of this server: -->{{ owner }}<--"

- set_fact: full_message"{{ message1 }} {{ message2 }} from {{ owner }}"

- debug:
   var: full_message

- debug:
   var: ansible_distribution

- shell: uptime 
  register: results 

- debug:
    var: results
 
#platbook,with many different variables
